// game_manager.dart
import 'dart:convert';

import '../models.dart';

//import 'package:flutter/material.dart';
import '../defines.dart';

import 'package:json_annotation/json_annotation.dart';

part 'game_state.g.dart';

@JsonSerializable()
class GameState {
  int turn = 0; // current turn
  bool turn_active = false;

  List<String> players = [];

  // Use ValueNotifier to notify listeners when the list changes
  Character? character_selected = null;

  // Use ValueNotifier to notify listeners when the list changes
  List<Character> characters = []; // List<Character>([]);

  GameState({
    required this.turn,
    required this.turn_active,
    required this.players,
    this.character_selected,
    required this.characters,
  });

  // Serialization logic (auto-generated by build_runner)
  factory GameState.fromJson(Map<String, dynamic> json) => _$GameStateFromJson(json);
  factory GameState.fromJsonString(String json_str) => _$GameStateFromJson(jsonDecode(json_str));

  Map<String, dynamic> toJson() => _$GameStateToJson(this);

  String Stringify() {
    return jsonEncode(this);
  }
  
}
